/* @LICENSE(NICTA) */

/* This header was generated by kernel/tools/invocation_header_gen.py.
 *
 * To add an invocation call number, edit libsel4/include/interfaces/sel4.xml.
 *
 */
#ifndef __LIBSEL4_INVOCATION_H
#define __LIBSEL4_INVOCATION_H

enum invocation_label {
    InvalidInvocation,
    UntypedRetype,
    TCBReadRegisters,
    TCBWriteRegisters,
    TCBCopyRegisters,
    TCBConfigure,
    TCBSetPriority,
    TCBSetMCPriority,
    TCBSetIPCBuffer,
    TCBSetSpace,
    TCBSuspend,
    TCBResume,
    TCBBindNotification,
    TCBUnbindNotification,
#if CONFIG_MAX_NUM_NODES > 1
    TCBSetAffinity,
#endif
#if defined(CONFIG_HARDWARE_DEBUG_API)
    TCBSetBreakpoint,
#endif
#if defined(CONFIG_HARDWARE_DEBUG_API)
    TCBGetBreakpoint,
#endif
#if defined(CONFIG_HARDWARE_DEBUG_API)
    TCBUnsetBreakpoint,
#endif
#if defined(CONFIG_HARDWARE_DEBUG_API)
    TCBConfigureSingleStepping,
#endif
    CNodeRevoke,
    CNodeDelete,
    CNodeCancelBadgedSends,
    CNodeCopy,
    CNodeMint,
    CNodeMove,
    CNodeMutate,
    CNodeRotate,
    CNodeSaveCaller,
    IRQIssueIRQHandler,
    IRQAckIRQ,
    IRQSetIRQHandler,
    IRQClearIRQHandler,
    DomainSetSet,
    nInvocationLabels
};
#include <sel4/sel4_arch/invocation.h>
#include <sel4/arch/invocation.h>

#endif /* __LIBSEL4_INVOCATION_H */
