/* @LICENSE(NICTA) */

/* This header was generated by kernel/tools/invocation_header_gen.py.
 *
 * To add an invocation call number, edit libsel4/include/interfaces/sel4.xml.
 *
 */
#ifndef __LIBSEL4_SEL4_ARCH_INVOCATION_H
#define __LIBSEL4_SEL4_ARCH_INVOCATION_H
enum sel4_arch_invocation_label {
    nSeL4ArchInvocationLabels = nInvocationLabels
};

#endif /* __LIBSEL4_SEL4_ARCH_INVOCATION_H */
